# Generated by Django 5.2.3 on 2025-06-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Contenido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Imagen',
            field=models.ImageField(upload_to='img_servicios'),
        ),
    ]
